name: 'Create Issue From File'
description: 'An action to create an issue using content from a file'
inputs:
  token:
    description: 'The GitHub authentication token'
    default: ${{ github.token }}
  repository:
    description: 'The target GitHub repository'
    default: ${{ github.repository }}
  update-existing:
    description: 'Update an open existing issue with the same title if it exists'
    required: false
    default: false
  issue-number:
    description: 'The issue number of an existing issue to update'
  title:
    description: 'The title of the issue'
    required: true
  content-filepath:
    description: 'The file path to the issue content'
  labels:
    description: 'A comma or newline-separated list of labels'
  assignees:
    description: 'A comma or newline-separated list of assignees (GitHub usernames)'
outputs:
  issue-number:
    description: 'The number of the created issue'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'alert-circle'
  color: 'orange'
